### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by kautukkundan** [Tenderly/tenderly-actions#15]
Is there any resource available on how to write and run tests asides from whats mentioned [here](https://docs.tenderly.co/web3-actions/functions#development-and-testing). Would be great if an end-to-end example could be provided.

**Comment by dzimiks** [comment]
Hey @kautukkundan! 👋

We recently published an [Example repository for Web3 Actions](https://github.com/Tenderly/examples-web3-actions) where you can find test examples as well, e.g.

- [Tic-Tac-Toe Tests](https://github.com/Tenderly/examples-web3-actions/blob/main/tic-tac-toe/actions/tests/ticTacToe.spec.ts) - This example shows how to listen to on-chain events in Web3 Actions. Events are fired by a Smart Contract representing a tic-tac-toe game and consumed by Web3 Actions, doing additional processing.
- [Uniswap Notify Discord Tests](https://github.com/Tenderly/examples-web3-actions/blob/main/uniswap-notify-discord/actions/tests/swap.test.ts) - How to send a Discord message about a new Uniswap Pool?

We plan to update our Docs in the near future, so more examples will be added as well. 👌 

I hope this will be helpful for you! 🎉

**Comment by kautukkundan** [comment]
Hey, thanks so much! I'll check these out 😄
